'''
Script to plot timeseries generated by kinematic_dynamo.py

Usage:
    plot_timeseries.py <folders>... 

Example:
    python3 plot_timeseries.py data_*
'''

import re
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

plt.rcParams.update({
    "figure.figsize": (6, 3.6),
    "font.size": 11
    })

def main(folders):
    for folder in folders:
        with h5py.File(f'{folder}/timeseries/timeseries_s1.h5', 'r') as file:
            Rm_search = re.search(r'Rm_([0-9.+\-eE]+)', str(folder))
            Rm = float(Rm_search.group(1))
            A_int = file['tasks/A_int']
            t = A_int.dims[0][0][:]
            plt.plot(t, A_int[:].squeeze(), label=fr'$Rm={Rm:.2f}$')
    plt.xlabel(r'$t$')
    plt.ylabel(r'$\|A\|^2/V$')
    plt.legend()
    plt.savefig('timeseries.pdf', bbox_inches='tight')

if __name__ == "__main__":
    from docopt import docopt
    args = docopt(__doc__)
    main(args['<folders>'])
